import React from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, LineChart, Line, PieChart, Pie, Cell } from 'recharts';

const activityData = [
  { name: 'Sector Alpha', Human: 12, Animal: 45, Vehicle: 5 },
  { name: 'Sector Bravo', Human: 4, Animal: 30, Vehicle: 2 },
  { name: 'North Gate', Human: 20, Animal: 15, Vehicle: 18 },
  { name: 'River Basin', Human: 2, Animal: 60, Vehicle: 0 },
];

const timeData = [
  { time: 'Week 1', incidents: 45 },
  { time: 'Week 2', incidents: 52 },
  { time: 'Week 3', incidents: 38 },
  { time: 'Week 4', incidents: 65 },
];

const pieData = [
  { name: 'Animal', value: 150 },
  { name: 'Human', value: 38 },
  { name: 'Vehicle', value: 25 },
];

const COLORS = ['#0B6623', '#ef4444', '#f59e0b'];

export const ReportTemplate = React.forwardRef<HTMLDivElement, {}>((props, ref) => {
  return (
    <div ref={ref} className="bg-white text-black p-8 w-[800px] h-auto flex flex-col gap-6" style={{ fontFamily: 'sans-serif' }}>
      
      {/* Header */}
      <div className="border-b-2 border-emerald-500 pb-4 mb-4">
        <h1 className="text-3xl font-bold text-slate-900">Wildlife Monitoring & Activity Analysis Report</h1>
        <p className="text-slate-600 mt-2">Generated by THE SAVIOUR AI Surveillance System</p>
        <p className="text-sm font-semibold text-emerald-600 mt-1">Time Range: Last 30 Days</p>
      </div>

      {/* Summary */}
      <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
        <h2 className="text-lg font-bold text-slate-800 mb-2">Executive Summary</h2>
        <ul className="list-disc pl-5 text-sm space-y-1 text-slate-700">
          <li>Highest human activity detected in <strong>North Gate</strong> (20 incidents).</li>
          <li>Animal movement highest in <strong>River Basin</strong> (60 detections).</li>
          <li>Overall threat level remained stable, with a 15% decrease in unauthorized vehicle movement.</li>
        </ul>
      </div>

      {/* Geo Analysis */}
      <div>
        <h2 className="text-lg font-bold text-slate-800 mb-2 border-b border-slate-200 pb-1">Geo Analysis & Hotspots</h2>
        <table className="w-full text-sm text-left border-collapse">
          <thead>
            <tr className="bg-slate-100">
              <th className="border border-slate-300 p-2">Location Name</th>
              <th className="border border-slate-300 p-2">Coordinates</th>
              <th className="border border-slate-300 p-2">Risk Level</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border border-slate-300 p-2">Sector Alpha</td>
              <td className="border border-slate-300 p-2 font-mono">29.5350, 78.7700</td>
              <td className="border border-slate-300 p-2 text-emerald-600">Moderate</td>
            </tr>
            <tr>
              <td className="border border-slate-300 p-2">North Gate</td>
              <td className="border border-slate-300 p-2 font-mono">29.5400, 78.7900</td>
              <td className="border border-slate-300 p-2 text-red-600">High</td>
            </tr>
            <tr>
              <td className="border border-slate-300 p-2">River Basin</td>
              <td className="border border-slate-300 p-2 font-mono">29.5250, 78.7850</td>
              <td className="border border-slate-300 p-2 text-emerald-600">Low</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Charts Grid */}
      <div className="grid grid-cols-2 gap-4 mt-4">
        
        <div className="border border-slate-200 p-4 rounded-lg">
          <h3 className="text-sm font-bold text-center mb-4 text-slate-700">Activity Over Time (30 Days)</h3>
          <LineChart width={320} height={200} data={timeData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="time" fontSize={10} />
            <YAxis fontSize={10} />
            <Line type="monotone" dataKey="incidents" stroke="#ef4444" strokeWidth={2} />
          </LineChart>
        </div>

        <div className="border border-slate-200 p-4 rounded-lg">
          <h3 className="text-sm font-bold text-center mb-4 text-slate-700">Distribution by Type</h3>
          <PieChart width={320} height={200}>
            <Pie data={pieData} cx="50%" cy="50%" outerRadius={60} fill="#8884d8" dataKey="value" label={({name, percent}) => `${name} ${((percent || 0) * 100).toFixed(0)}%`}>
              {pieData.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
              ))}
            </Pie>
          </PieChart>
        </div>

        <div className="col-span-2 border border-slate-200 p-4 rounded-lg">
          <h3 className="text-sm font-bold text-center mb-4 text-slate-700">Area-wise Activity Breakdown</h3>
          <BarChart width={700} height={250} data={activityData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="name" fontSize={12} />
            <YAxis fontSize={12} />
            <Legend wrapperStyle={{ fontSize: '12px' }}/>
            <Bar dataKey="Animal" fill="#0B6623" />
            <Bar dataKey="Human" fill="#ef4444" />
            <Bar dataKey="Vehicle" fill="#f59e0b" />
          </BarChart>
        </div>

      </div>

      <div className="mt-8 text-center text-xs text-slate-400 border-t border-slate-200 pt-4">
        Generated automatically by The Saviour Analytics Engine on {new Date().toLocaleDateString()}
      </div>

    </div>
  );
});

ReportTemplate.displayName = 'ReportTemplate';
